version: '3.4'
services:
  app:
    image: '${IMAGE_LOCAL}'
    build:
      context: ./
      target: '${TARGET_LOCAL}'
    entrypoint: bash -c '${COMMAND_LOCAL}'
    ports:
      - '${PORT_HOST}:${PORT_APP}'
    volumes:
      - './:/app'