version: '3.4'
services:
  app:
    image: '${IMAGE}'
    build:
      context: ./
      target: '${TARGET}'
    entrypoint: bash -c '${COMMAND}'
    ports:
      - '${PORT_HOST}:${PORT_APP}'
    volumes:
      - './:/app'