name: Deploy - main-dev
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
    
jobs:
  Deploy:
    name: Deploy to EC2
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST_DEV}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.USER_NAME}}@${{secrets.SSH_HOST_PROD}} '
          touch 4444.txt
          echo "Hello World 4444"

