name: Deploy
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  Build_image_and_publish:
    runs-on: ubuntu-latest 
    name: Build and Push image
    steps:
      - uses: actions/checkout@v3 
      - name: Build & Push image
        run: |
          docker login -u "francesco.re69@gmail.com" -p "Lillone19" docker.io
          docker build --target development -t 3481974/name-development:tag-development .
          docker push docker.io/3481974/name-development:tag-development
          
  Deploy:
    needs: Build_image_and_publish
    name: Deploy to main
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy      
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.USER_NAME}}@${{secrets.SSH_HOST_PROD}} '
          touch 99999999911.txt
          docker login -u "francesco.re69@gmail.com" -p "Lillone19" docker.io
          docker pull docker.io/3481974/name-development:tag-development
          docker run -d -p 3897:4000 --name nodejsonline 3481974/name-development:tag-development
          '

